from __future__ import annotations

import uuid
from typing import TypedDict


CATALOG_NAMESPACE = uuid.UUID("e52df69d-dc73-4a8f-8ae9-cbecf8ce7ad7")

ADMIN_EMAIL = "admin@example.org"
ADMIN_PASSWORD = "Admin123!"

DIFFICULTIES: list[tuple[str, float]] = [
    ("very easy", 0.25),
    ("easy", 0.75),
    ("medium", 1.5),
    ("hard", 2.25),
    ("very hard", 3.0),
]

TOPIC_SUBTOPICS: dict[str, list[str]] = {
    "Planimetry": [
        "right triangle",
        "isosceles triangle",
        "general triangle",
        "parallelograms",
        "trapezoids",
        "central and inscribed angles",
        "tangent, chord, secant",
        "incircle / inscribed circle",
        "circumcircle / circumscribed circle",
    ],
    "Vectors": [
        "vector coordinates",
        "addition and subtraction of vectors",
        "multiplication of a vector by a scalar",
        "vector length",
        "equality / collinearity of vectors",
        "scalar product",
        "angle between vectors",
    ],
    "Stereometry": [
        "cube",
        "rectangular parallelepiped / cuboid",
        "elements of composite polyhedra",
        "surface area of a composite polyhedron",
        "volume of a composite polyhedron",
        "prism",
        "pyramid",
        "combinations of solids",
        "cylinder",
        "cone",
        "sphere",
    ],
    "Basic probability": [
        "classical definition of probability",
        "equally likely outcomes",
        "counting favorable outcomes",
        "simple combinatorial counting inside probability",
        "direct probability from a table / simple selection model",
    ],
    "Complex probability / probability theorems": [
        "complement event",
        "addition rule for probabilities",
        "multiplication rule for probabilities",
        "conditional probability",
        "independent events",
        "Bernoulli trials / Bernoulli formula",
        "probability trees / graphical case splits",
        "full-probability style case splitting",
        "mixed harder probability situations",
    ],
    "Elementary equations": [
        "linear equations",
        "quadratic equations",
        "cubic equations",
        "rational equations",
        "irrational equations",
        "exponential equations",
        "logarithmic equations",
        "trigonometric equations",
    ],
    "Computation and algebraic transformations": [
        "transformations of numerical rational expressions",
        "transformations of algebraic expressions and fractions",
        "evaluation of power expressions",
        "laws of exponents",
        "transformations of numerical irrational expressions",
        "transformations of literal irrational expressions",
        "transformations of numerical logarithmic expressions",
        "transformations of literal logarithmic expressions",
        "evaluation of trigonometric expressions",
        "transformations of numerical trigonometric expressions",
        "transformations of literal trigonometric expressions",
    ],
    "Derivative and antiderivative": [
        "physical meaning of derivative",
        "geometric meaning of derivative",
        "tangent line",
        "using derivative to investigate a function",
        "antiderivative",
        "basic integral / area of a curvilinear trapezoid",
    ],
    "Applied modeling task": [
        "linear equations and inequalities in context",
        "quadratic and power equations / inequalities in context",
        "rational equations / inequalities in context",
        "irrational equations / inequalities in context",
        "exponential equations / inequalities in context",
        "logarithmic equations / inequalities in context",
        "trigonometric equations / inequalities in context",
        "other applied modeling tasks",
    ],
    "Word problems": [
        "percentages",
        "alloys and mixtures",
        "motion on a line",
        "circular motion",
        "motion on water",
        "joint work / productivity",
        "progressions in context",
    ],
    "Graphs of functions": [
        "linear functions",
        "parabolas",
        "hyperbolas",
        "root functions",
        "exponential functions",
        "logarithmic functions",
        "trigonometric functions",
        "combined / mixed graph-identification tasks",
    ],
    "Greatest / least value of a function": [
        "investigation without derivative",
        "power functions",
        "irrational functions",
        "quotients",
        "products",
        "exponential functions",
        "logarithmic functions",
        "trigonometric functions",
    ],
    "Advanced equations": [
        "exponential equations",
        "rational equations",
        "irrational equations",
        "logarithmic equations",
        "trigonometric equations reducible to quadratic form",
        "trigonometric equations reducible to homogeneous form",
        "trigonometric equations by factorization",
        "trigonometric equations with domain / ODZ analysis",
        "miscellaneous trigonometric equations",
        "trig + irrational mixed equations",
        "trig + logarithmic mixed equations",
        "trig + exponential mixed equations",
        "other mixed-type equations",
    ],
    "Advanced stereometry": [
        "distance between lines and planes",
        "distance between points; point to line",
        "distance from point to plane",
        "sections of pyramids",
        "sections of prisms",
        "sections of parallelepipeds",
        "angle between planes",
        "angle between faces of a polyhedron",
        "angle between a line and a plane",
        "angle between skew lines",
        "volumes of polyhedra",
        "sections of bodies of revolution",
        "cylinder / cone / sphere in stereometric setups",
        "combinations of figures / solids",
    ],
    "Inequalities": [
        "radical inequalities",
        "rational inequalities",
        "exponential inequalities",
        "inequalities rational in an exponential function",
        "logarithmic inequalities of first and second degree",
        "inequalities rational in a logarithmic function",
        "inequalities with logarithms of variable base",
        "variable-base logarithmic inequalities with rationalization",
        "mixed logarithmic inequalities",
        "exponential + irrational mixed inequalities",
        "logarithmic + exponential mixed inequalities",
        "logarithmic + irrational mixed inequalities",
        "trigonometric inequalities",
        "inequalities with modulus",
        "other mixed-type inequalities",
    ],
    "Financial mathematics": [
        "deposits / savings / capitalization",
        "deposits with extra contributions or withdrawals",
        "loans / credits",
        "annuity (equal-payment) credit schemes",
        "differentiated / residual-schedule credit schemes",
        "finding rate, term, payment, principal, or remaining debt",
        "optimal choice between tariffs / plans",
        "other financial-practical tasks",
        "production / profit optimization in an economic context",
    ],
    "Advanced planimetry": [
        "triangles and their properties",
        "quadrilaterals and their properties",
        "circles and systems of circles",
        "incircles and triangles",
        "circumcircles and triangles",
        "mixed circle-triangle problems",
        "incircles and quadrilaterals",
        "circumcircles and quadrilaterals",
        "mixed circle-quadrilateral problems",
        "miscellaneous polygon problems",
    ],
    "Problems with a parameter": [
        "equations with a parameter",
        "equations with a parameter containing modulus",
        "equations with a parameter containing radicals",
        "inequalities with a parameter",
        "systems with a parameter",
        "location of roots of a quadratic trinomial",
        "use of symmetry",
        "use of monotonicity and estimates",
        "analytic solution of equations and inequalities",
        "analytic solution of systems",
        "coordinate-plane method in (x, a)",
        "circle equation in parameter problems",
        "distance between points in parameter problems",
        "functions depending on a parameter",
    ],
    "Numbers and their properties": [
        "divisibility",
        "divisibility criteria",
        "parity / odd-even arguments",
        "remainders / modular reasoning",
        "greatest common divisor and least common multiple",
        "prime and composite numbers",
        "factorization / fundamental theorem of arithmetic",
        "decimal representation and digit properties",
        "sequences and progressions",
        "number sets on cards / boards",
        "story-style discrete problems (cinema / theater / rope type families)",
        "constructive existence examples",
        "impossibility proofs",
        "estimate + example style arguments",
    ],
}

SKILL_SUBSKILLS: dict[str, list[str]] = {
    "Numbers and expressions": [
        "compare and estimate real numbers",
        "compute with fractions and signed numbers",
        "convert fractions, decimals, and percentages",
        "simplify power expressions",
        "simplify radical expressions",
        "simplify algebraic fractions",
        "factor algebraic expressions",
        "simplify logarithmic expressions",
        "simplify trigonometric expressions",
    ],
    "Equations": [
        "solve linear equations",
        "solve quadratic equations",
        "solve rational equations",
        "solve irrational equations",
        "solve exponential equations",
        "solve logarithmic equations",
        "solve trigonometric equations",
        "solve systems of equations",
        "remove extraneous roots by checking restrictions",
    ],
    "Inequalities": [
        "solve linear inequalities",
        "solve quadratic inequalities",
        "solve rational inequalities by interval method",
        "solve irrational inequalities",
        "solve exponential inequalities",
        "solve logarithmic inequalities",
        "solve trigonometric inequalities",
        "solve inequalities with modulus",
        "solve systems of inequalities",
    ],
    "Functions, graphs, derivative, antiderivative": [
        "find the domain of a function",
        "read values and properties from a graph",
        "recognize graphs of standard functions",
        "apply graph transformations",
        "determine intervals of increase and decrease",
        "find extrema of a function",
        "find greatest or least value on an interval",
        "use the geometric meaning of the derivative",
        "write the tangent-line equation",
        "use the derivative to investigate a function",
        "use the physical meaning of the derivative",
        "use an antiderivative to find area",
    ],
    "Text and financial modeling": [
        "model percentage problems",
        "model mixture and alloy problems",
        "model motion on a line",
        "model motion on water",
        "model work-rate problems",
        "model progression-based word problems",
        "calculate compound growth of a deposit",
        "model loan repayment",
        "compare financial plans and choose the optimum",
    ],
    "Probability, combinatorics, statistics": [
        "count elementary outcomes",
        "compute classical probability",
        "use complement probability",
        "use addition of probabilities",
        "use multiplication of probabilities",
        "work with independent events",
        "work with conditional probability",
        "solve repeated-trial probability problems",
        "count permutations and combinations",
        "read tables, charts, and statistical data",
    ],
    "Planimetry": [
        "solve right-triangle configurations",
        "use triangle similarity",
        "use triangle congruence",
        "use medians, bisectors, and altitudes",
        "solve quadrilateral and trapezoid configurations",
        "use properties of central and inscribed angles",
        "use tangent, chord, and secant relations",
        "use properties of an incircle",
        "use properties of a circumcircle",
        "compute lengths and areas in plane figures",
    ],
    "Vectors and stereometry": [
        "represent a vector in coordinates",
        "add and subtract vectors",
        "multiply a vector by a scalar",
        "find vector length",
        "use the scalar product",
        "find the angle between vectors",
        "compute surface area of solids",
        "compute volume of solids",
        "solve sections of prisms and pyramids",
        "find an angle between lines and planes in space",
        "find distances in space",
        "solve combined-solid problems",
    ],
    "Parameters and numbers": [
        "solve equations with a parameter",
        "solve inequalities with a parameter",
        "solve systems with a parameter",
        "analyze the location of roots of a quadratic",
        "use monotonicity in parameter problems",
        "use symmetry in parameter problems",
        "use the coordinate plane (x, a) in parameter problems",
        "prove divisibility statements",
        "use parity arguments",
        "solve remainder problems",
        "use prime factorization",
        "find gcd and lcm",
        "analyze digit properties of integers",
        "solve sequence and progression problems",
    ],
}


class AnswerOptionSeed(TypedDict):
    text: str
    is_correct: bool


class ProblemSubskillSeed(TypedDict):
    name: str
    weight: float


class ProblemSeed(TypedDict):
    key: str
    subtopic: str
    difficulty: str
    condition: str
    solution: str
    condition_images: list[str]
    solution_images: list[str]
    answer_options: list[AnswerOptionSeed]
    subskills: list[ProblemSubskillSeed]


SAMPLE_PROBLEMS: list[ProblemSeed] = [
    {
        "key": "planimetry-area",
        "subtopic": "right triangle",
        "difficulty": "easy",
        "condition": "In a right triangle, the legs are 6 and 8. Find the area of the triangle.",
        "solution": "The area of a right triangle is \\\\frac{1}{2}ab. Therefore, S=\\\\frac{1}{2}\\\\cdot 6 \\\\cdot 8 = 24.",
        "condition_images": [],
        "solution_images": [],
        "answer_options": [
            {"text": "20", "is_correct": False},
            {"text": "24", "is_correct": True},
            {"text": "28", "is_correct": False},
            {"text": "48", "is_correct": False},
        ],
        "subskills": [
            {"name": "solve right-triangle configurations", "weight": 0.7},
            {"name": "compute lengths and areas in plane figures", "weight": 0.3},
        ],
    },
    {
        "key": "vectors-scalar-product",
        "subtopic": "scalar product",
        "difficulty": "medium",
        "condition": "Given vectors a=(2,-1) and b=(3,4), find the scalar product a \\\\cdot b.",
        "solution": "The scalar product equals 2\\\\cdot 3 + (-1)\\\\cdot 4 = 6-4=2.",
        "condition_images": [],
        "solution_images": [],
        "answer_options": [
            {"text": "-2", "is_correct": False},
            {"text": "2", "is_correct": True},
            {"text": "10", "is_correct": False},
            {"text": "14", "is_correct": False},
        ],
        "subskills": [
            {"name": "represent a vector in coordinates", "weight": 0.4},
            {"name": "use the scalar product", "weight": 0.6},
        ],
    },
    {
        "key": "log-equation",
        "subtopic": "logarithmic equations",
        "difficulty": "hard",
        "condition": "Solve the equation \\\\log_2(x-1)=3.",
        "solution": "From \\\\log_2(x-1)=3 we get x-1=2^3=8, so x=9. The restriction x>1 is satisfied.",
        "condition_images": [],
        "solution_images": [],
        "answer_options": [
            {"text": "7", "is_correct": False},
            {"text": "8", "is_correct": False},
            {"text": "9", "is_correct": True},
            {"text": "10", "is_correct": False},
        ],
        "subskills": [
            {"name": "solve logarithmic equations", "weight": 0.7},
            {"name": "remove extraneous roots by checking restrictions", "weight": 0.3},
        ],
    },
    {
        "key": "derivative-slope",
        "subtopic": "tangent line",
        "difficulty": "medium",
        "condition": "For f(x)=x^2, find the slope of the tangent line at x=3.",
        "solution": "The derivative is f'(x)=2x. At x=3 we have f'(3)=6, so the slope equals 6.",
        "condition_images": [],
        "solution_images": [],
        "answer_options": [
            {"text": "3", "is_correct": False},
            {"text": "6", "is_correct": True},
            {"text": "9", "is_correct": False},
            {"text": "12", "is_correct": False},
        ],
        "subskills": [
            {"name": "use the geometric meaning of the derivative", "weight": 0.7},
            {"name": "write the tangent-line equation", "weight": 0.3},
        ],
    },
]


def build_stable_uuid(scope: str, value: str) -> uuid.UUID:
    return uuid.uuid5(CATALOG_NAMESPACE, f"{scope}:{value}")
